FROM php:8.2-apache

# Installe les dépendances
RUN apt-get update && \
    apt-get install -y \
        nano \
        wget \
        unzip \
        libzip-dev \
        libicu-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libpq-dev \
        zlib1g-dev \
        libonig-dev

# Installe Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Configure Xdebug
RUN echo 'xdebug.mode=debug' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo 'xdebug.client_host=host.docker.internal' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo 'xdebug.client_port=9003' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Installe les extensions PHP nécessaires
RUN docker-php-ext-install \
        pdo_mysql \
        zip \
        intl \
        gd

RUN echo "<?php phpinfo(); ?>" >> /var/www/html/phpinfo.php