version: '3.8'

services:

  web89:
    image: php:8.2-apache
    container_name: apache123
    volumes:
      - ./docker/html:/var/www/html
    ports:
      - 82:80
    environment:
      - XDEBUG_CONFIG=remote_port=9000

  mysql:
    image: mysql:5.7
    container_name: mysql123
    environment:
      MYSQL_DATABASE: tp2
      MYSQL_USER: zinedine
      MYSQL_PASSWORD: Bonjour!
      MYSQL_ROOT_PASSWORD: aled
      UPLOAD_LIMIT: 20M
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/usr/local/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 83:80
    environment:
      - PMA_HOST=mysql

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'db'
    volumes:
        - ./docker/data:/var/lib/postgresql/data
    ports:
        - 54321:54321
    depends_on:
      - postgis
    command: >
        sh -c "while ! pg_isready -h db -p 5432 > /dev/null 2> /dev/null; do sleep 1; done && \
               psql -U example_user -d example_db -c 'CREATE EXTENSION postgis;'"

  postgis:
    image: postgis/postgis:13-3.2-alpine

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.com
      PGADMIN_DEFAULT_PASSWORD: Bonjour!
    ports:
      - "8080:80"